version: '3.7'
services:
  app:
    build: .
    image: golang:1.6.1-alpine
    restart: always
    ports:
      - 8080:8080
  db:
    image: keinos/sqlite3:latest
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql